config/routes.rb
Rails.application.routes.draw do
  resources :user_stocks, only: [:create, :destroy]
  resources :friendships, only: [:destroy]
  devise_for :users
  root 'welcome#index'
  get 'portfolio', to: 'users#portfolio'
  get 'search_stock', to: 'stocks#search'
  get 'friends', to: 'users#friends'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base

  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'
end

app/models/stock.rb
class Stock < ApplicationRecord
  has_many :user_stocks
  has_many :users, through: :user_stocks
  validates :name, :ticker, presence: true

  def self.new_lookup(ticker)
    client = IEX::Api::Client.new(
            publishable_token: Rails.application.credentials.iex[:publishable_token],
            secret_token: Rails.application.credentials.iex[:secret_token],
            endpoint: 'https://sandbox.iexapis.com/v1' )
    begin
      logo = client.logo(ticker)
     new(ticker: ticker, name: client.company(ticker).company_name,
     last_price: client.price(ticker), logo: logo.url)

    rescue => exception
     return nil
    end
  end

  def self.check_db(ticker)
    where(ticker: ticker).first
  end
end

app/models/user.rb
class User < ApplicationRecord
    has_many :user_stocks
    has_many :stocks, through: :user_stocks
    has_many :friendships
    has_many :friends, through: :friendships

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def stock_already_tracked?(ticker)
    stock = Stock.check_db(ticker)
    return false unless stock
    stocks.where(id: stock.id).exists?
  end
  def under_stock_limit?
    stocks.count < 10
  end

  def can_track_stock?(ticker)
    under_stock_limit? && !stock_already_tracked?(ticker)
  end

  def full_name
    if first_name || last_name
      return "#{first_name} #{last_name}"
    else
      return "Anonymous"
    end
  end
end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

 protected

 def configure_permitted_parameters
   devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :username])
   devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :username])
 end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def destroy
    friend = Friendship.where(user_id: current_user.id,friend_id: params[:id] ).first
    friend.destroy
    flash[:notice] = "Friend was successfully removed from portfolio"
    redirect_to friends_path
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  def search
    if params[:stock].present?
      @stock = Stock.new_lookup(params[:stock])
      if @stock
        respond_to do |format|
          format.js { render partial: 'users/result'}
        end
      else
        respond_to do |format|
            flash.now[:alert] = "Please enter a valid symbol"
          format.js { render partial: 'users/result'}
        end
      end
    else
      respond_to do |format|
        flash.now[:alert] = "Please enter a symbol to search"
        format.js { render partial: 'users/result'}
      end

    end
  end
end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController
  def create
    stock = Stock.check_db(params[:ticker].upcase)
    if stock.blank?
      stock = Stock.new_lookup(params[:ticker].upcase)
      stock.save
    end

    @user_stock = UserStock.create(user: current_user, stock: stock)
    flash[:notice] = "Stock #{stock.name} was succesfully added to your portfolio"
    redirect_to portfolio_path

  end

  def destroy
    stock = Stock.find(params[:id])
    user_stock = UserStock.where(user_id: current_user.id,stock_id: stock.id ).first
    user_stock.destroy
    flash[:notice] = "Stock #{stock.ticker} was successfully removed from portfolio"
    redirect_to portfolio_path
  end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def portfolio
    @tracked_stocks = current_user.stocks
  end
  def friends
    @friends = current_user.friends
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_messages.html.erb
<% flash.each do |name,msg| %>
<% if name == "notice" %>
<p class="notice"><div class="alert alert-success alert-dismissible fade show" role="alert">
<%= msg %>
<button type="button" class="close" data-dismiss="alert" aria-label="Close">
  <span aria-hidden="true">&times;</span>
</button>
</div>
</div></p>
<% else %>
 <p class="alert"><div class="alert alert-danger alert-dismissible fade show" role="alert">
<%= msg %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
</div></p>
<% end %>
<% end %>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">

    <a class="navbar-brand" href="<%= portfolio_path %>">Finance Tracker</a>
    <% if current_user %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item <%= 'active' if request.path == portfolio_path %>">
          <%= link_to "My Porfolio", portfolio_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= friends_path %>">My Friends</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
           Profile
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li>
              <%= link_to "Edit Profile", edit_user_registration_path, class: "dropdown-item" %>
            </li>
            <li>
              <%= link_to edit_user_registration_path, class: "dropdown-item" do %>
              <i class="fas fa-edit"></i> Edit profile
              <% end %>
            </li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link">Disabled</a>
        </li>
      </ul>
      <ul class='navbar-nav ml-auto'>
        <li class='nav-item user-name'>
          <i class="fas fa-user-tie"></i> <%= current_user.full_name %>
        </li>
        <li class='nav-item'>
            <%= link_to("Logout", destroy_user_session_path,
            class: "btn btn-xs btn-danger logout-button", method: :delete) %>
          </li>
        </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>

    <% end %>
  </div>

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinanceTracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/messages' %>
    <%= render 'layouts/nav' %>
    <div class="container" >


    <%= yield %>
    </div>
  </body>
</html>

app/views/stocks/_list.html.erb
<% if !@tracked_stocks.empty? %>
<div class="col-9" >
  <div class="results-block">
    <%= render 'layouts/messages' %>
  </div>
  <table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th scope="col">Ticker</th>
      <th scope="col">Name</th>
      <th scope="col">Price</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @tracked_stocks.each do |stock| %>
    <tr>
      <th scope="row"><%= stock.ticker %></th>
      <td><%= stock.name %></td>
      <td><%= stock.last_price %></td>
      <td><%= link_to "Remove", user_stock_path(stock), method: :delete, data: {confirm: "Are you sure"}, class: "btn btn-danger" %></td>
    </tr>
    <% end %>
  </tbody>
</table>
</div>
<% end %>

app/views/users/_friends.html.erb
<% if !@friends.empty? %>
<div class="col-9" >
  <div class="results-block">
    <%= render 'layouts/messages' %>
  </div>
  <table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th scope="col">Username</th>
      <th scope="col">Fullname</th>
      <th scope="col">Email</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @friends.each do |friend| %>
    <tr>
      <th scope="row"><%= friend.username %></th>
      <td><%= friend.full_name %></td>
      <td><%= friend.email %></td>
      <td><%= link_to "Stop Following", friendship_path(friend), method: :delete, data: {confirm: "Are you sure"}, class: "btn btn-danger" %></td>
    </tr>
    <% end %>
  </tbody>
</table>
</div>
<% end %>

app/views/users/_result.html.erb
alert("Hello World");

app/views/users/_result.js.erb
document.querySelector('#results').innerHTML = '<%= j render 'users/stock.html' %>'

app/views/users/_stock.html.erb
<div class="results-block">
  <%= render 'layouts/messages' %>
</div>
<% if @stock %>
<div class="card card-header results-block">
<strong>Symbol: </strong> <%= @stock.ticker.upcase %>
<strong>Name: </strong> <%= @stock.name %>
<strong>Price: </strong> <%= @stock.last_price %>
<strong>Logo: </strong> <%= @stock.logo %>
<% if current_user.can_track_stock?(@stock.ticker) %>
<%= link_to "Add to portfolio", user_stocks_path(user: current_user, ticker: @stock.ticker),
class: "btn btn-success", method: :post %>
<% else %>
<span class="badge badge-secondary text-primary"> You are already tracking
<% if !current_user.under_stock_limit? %>
10 Stocks
<% end %>
<% if current_user.stock_already_tracked?(@stock.ticker) %>
this stock
<% end %>
 </span>
</div>
<% end %>
<% end %>

app/views/users/friends.html.erb
<h1>Friends</h1>

<%= render 'users/friends' %>

app/views/users/portfolio.html.erb
<h1>Portfolio</h1>
<div class="search-area">
<h3>Search Stocks</h3>
<%= form_tag search_stock_path, remote: true, method: :get do %>
  <div class="form=group row" >
    <div class="col-sm-9">
      <%= text_field_tag :stock, params[:stock],  placeholder: "Stock ticker symbol",
      autofocus: true, class: "form-control form-control-lg" %>
    </div>
    <div class="col-sm-3">
      <%= button_tag type: :submit, class: "btn btn-success" do %>
      <%= "Search" %>
      <% end %>
    </div>
  </div>
<% end %>
</div>
<div id="results" >
<%= render 'users/stock' %>
</div>
<%= render 'stocks/list' %>

app/views/welcome/index.html.erb
<div class="container" id="home-container">
<div class="jumbotron text-center">
  <h1 class="display-4">Finance Tracker</h1>
  <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
  <hr class="my-4">
  <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
  <% if !current_user %>
  <%= link_to "Sign up!", new_user_registration_path, class: "btn btn-primary btn-lg" %>
  <%= link_to "Login", new_user_session_path, class: "btn btn-primary btn-lg" %>
  <% end %>
</div>
</div>